name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ci_cd
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, sqlite, curl, zip, gd, intl, bcmath, soap, redis, xdebug
        coverage: xdebug

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Set up environment variables
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=ci_cd" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=root" >> .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..10}; do
          if mysql -h 127.0.0.1 -u root -proot -e "SELECT 1;" > /dev/null 2>&1; then
            echo "MySQL is ready!"
            break
          else
            echo "Waiting for MySQL to start..."
            sleep 5
          fi
        done

    - name: Test MySQL connection
      run: mysql -h 127.0.0.1 -u root -proot -e "SHOW DATABASES;"

    - name: Check MySQL logs
      run: docker logs $(docker ps -q --filter "ancestor=mysql:5.7")

    - name: Run migrations
      run: php artisan migrate --force

    